import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageTransition from "@/components/pageTransition";
import { AnimatePresence } from "framer-motion";
import { AppWrapper } from "@/context";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className='bg-[#F7F6F3]'>
          <AppWrapper>
          <Toaster />
          <Header />
            {children}
          </AppWrapper>
        </body>
    </html>
  );
}
